Docs: Contributing file add
computerclubkec/data-communication pull request #37
Opened 2023-11-12 08:45 UTC by aayush105

2023-11-12 11:37 UTC, gaurovgiri requested changes

2023-11-12 11:37 UTC, gaurovgiri commented on CONTRIBUTING.md
> +
Mention about installing the requirements

2023-11-12 11:37 UTC, gaurovgiri commented on CONTRIBUTING.md
> +
Raise an issue or get assigned for an existing issue, if you want to work on something.

2023-11-12 11:37 UTC, gaurovgiri commented on CONTRIBUTING.md
> +    ```
Open a pull request

2023-11-13 14:11 UTC, aayush105 commented
@gaurovgiri please review this, changes have been done and push again.

2023-11-13 14:13 UTC, gaurovgiri approved these changes
LGTM!

2023-11-13 14:15 UTC, merged